on:
  pull_request:
    types: [opened, synchronize]

name: Lint and Tests

jobs:
  test:
    name: Lint and Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run lint

